package com.quimera.corptextiljt.model;

// Generated Dec 23, 2017 11:54:35 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Acceso generated by hbm2java
 */
@Entity
@Table(name = "acceso", catalog = "jtextpricesbd")
public class Acceso implements java.io.Serializable {

	private Integer idacceso;
	private Rol rol;
	private Usuario usuario;

	public Acceso() {
	}

	public Acceso(Rol rol, Usuario usuario) {
		this.rol = rol;
		this.usuario = usuario;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDAcceso", unique = true, nullable = false)
	public Integer getIdacceso() {
		return this.idacceso;
	}

	public void setIdacceso(Integer idacceso) {
		this.idacceso = idacceso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rol_IDRol", nullable = false)
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_IDUsuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

}
