package com.quimera.corptextiljt.model;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Clasificaciontienda generated by hbm2java
 */
@Entity
@Table(name = "clasificaciontienda", catalog = "jtextpricesbd", uniqueConstraints = @UniqueConstraint(columnNames = "NombreClasificacionTienda"))
public class Clasificaciontienda implements java.io.Serializable {

	private Integer idclasificacionTienda;
	private String nombreClasificacionTienda;
	private Integer estatus;
	private Set<Tienda> tiendas = new HashSet<Tienda>(0);;

	public Clasificaciontienda() {
	}

	public Clasificaciontienda(String nombreClasificacionTienda, Integer estatus) {
		this.nombreClasificacionTienda = nombreClasificacionTienda;
		this.estatus = estatus;
	}

	public Clasificaciontienda(String nombreClasificacionTienda, Integer estatus,
			Set<Tienda> tiendas) {
		this.nombreClasificacionTienda = nombreClasificacionTienda;
		this.estatus = estatus;
		this.tiendas = tiendas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDClasificacionTienda", unique = true, nullable = false)
	public Integer getIdclasificacionTienda() {
		return this.idclasificacionTienda;
	}

	public void setIdclasificacionTienda(Integer idclasificacionTienda) {
		this.idclasificacionTienda = idclasificacionTienda;
	}

	@Column(name = "NombreClasificacionTienda", unique = true, nullable = false, length = 30)
	public String getNombreClasificacionTienda() {
		return this.nombreClasificacionTienda;
	}

	public void setNombreClasificacionTienda(String nombreClasificacionTienda) {
		this.nombreClasificacionTienda = nombreClasificacionTienda;
	}

	@Column(name = "Estatus", nullable = false)
	public Integer getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Integer estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clasificaciontienda")
	public Set<Tienda> getTiendas() {
		return this.tiendas;
	}

	public void setTiendas(Set<Tienda> tiendas) {
		this.tiendas = tiendas;
	}

}
