package com.quimera.corptextiljt.model;

// Generated Dec 23, 2017 11:54:35 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Logprecioproducto generated by hbm2java
 */
@Entity
@Table(name = "logprecioproducto", catalog = "jtextpricesbd")
public class Logprecioproducto implements java.io.Serializable {

	private int idlog;
	private Tipoprecio tipoprecio;
	private Usuario usuario;
	private Producto producto;
	private Date fechaLog;
	private double precioPrevio;
	private double nuevoPrecio;

	public Logprecioproducto() {
	}

	public Logprecioproducto(Tipoprecio tipoprecio, Usuario usuario,
			Producto producto, double precioPrevio, double nuevoPrecio) {
		this.tipoprecio = tipoprecio;
		this.usuario = usuario;
		this.producto = producto;
		this.precioPrevio = precioPrevio;
		this.nuevoPrecio = nuevoPrecio;
	}

	public Logprecioproducto(Tipoprecio tipoprecio, Usuario usuario,
			Producto producto, Date fechaLog, double precioPrevio,
			double nuevoPrecio) {
		this.tipoprecio = tipoprecio;
		this.usuario = usuario;
		this.producto = producto;
		this.fechaLog = fechaLog;
		this.precioPrevio = precioPrevio;
		this.nuevoPrecio = nuevoPrecio;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDLog", unique = true, nullable = false)
	public int getIdlog() {
		return this.idlog;
	}

	public void setIdlog(int idlog) {
		this.idlog = idlog;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipoprecio_IDTipoPrecio", nullable = false)
	public Tipoprecio getTipoprecio() {
		return this.tipoprecio;
	}

	public void setTipoprecio(Tipoprecio tipoprecio) {
		this.tipoprecio = tipoprecio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_IDUsuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "producto_IDProducto", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaLog", length = 19)
	public Date getFechaLog() {
		return this.fechaLog;
	}

	public void setFechaLog(Date fechaLog) {
		this.fechaLog = fechaLog;
	}

	@Column(name = "PrecioPrevio", nullable = false, precision = 8)
	public double getPrecioPrevio() {
		return this.precioPrevio;
	}

	public void setPrecioPrevio(double precioPrevio) {
		this.precioPrevio = precioPrevio;
	}

	@Column(name = "NuevoPrecio", nullable = false, precision = 8)
	public double getNuevoPrecio() {
		return this.nuevoPrecio;
	}

	public void setNuevoPrecio(double nuevoPrecio) {
		this.nuevoPrecio = nuevoPrecio;
	}

}
