package com.quimera.corptextiljt.model;

// Generated Dec 23, 2017 11:54:35 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Precioproducto generated by hbm2java
 */
@Entity
@Table(name = "precioproducto", catalog = "jtextpricesbd")
public class Precioproducto implements java.io.Serializable {

	private Integer idprecioProducto;
	private Usuario usuarioByUsuarioIdusuarioModifica;
	private Tipoprecio tipoprecio;
	private Usuario usuarioByUsuarioIdusuarioAlta;
	private Producto producto;
	private Tienda tienda;
	private double precioProducto;
	private Date fechaAlta;
	private Date fechaMod;
	private Integer estatus;

	public Precioproducto() {
	}

	public Precioproducto(Usuario usuarioByUsuarioIdusuarioModifica,
			Tipoprecio tipoprecio, Usuario usuarioByUsuarioIdusuarioAlta,
			Producto producto, Tienda tienda, double precioProducto, Integer estatus) {
		this.usuarioByUsuarioIdusuarioModifica = usuarioByUsuarioIdusuarioModifica;
		this.tipoprecio = tipoprecio;
		this.usuarioByUsuarioIdusuarioAlta = usuarioByUsuarioIdusuarioAlta;
		this.producto = producto;
		this.tienda = tienda;
		this.precioProducto = precioProducto;
		this.estatus = estatus;
	}

	public Precioproducto(Usuario usuarioByUsuarioIdusuarioModifica,
			Tipoprecio tipoprecio, Usuario usuarioByUsuarioIdusuarioAlta,
			Producto producto, Tienda tienda, double precioProducto,
			Date fechaAlta, Date fechaMod, Integer estatus) {
		this.usuarioByUsuarioIdusuarioModifica = usuarioByUsuarioIdusuarioModifica;
		this.tipoprecio = tipoprecio;
		this.usuarioByUsuarioIdusuarioAlta = usuarioByUsuarioIdusuarioAlta;
		this.producto = producto;
		this.tienda = tienda;
		this.precioProducto = precioProducto;
		this.fechaAlta = fechaAlta;
		this.fechaMod = fechaMod;
		this.estatus = estatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDPrecioProducto", unique = true, nullable = false)
	public Integer getIdprecioProducto() {
		return this.idprecioProducto;
	}

	public void setIdprecioProducto(Integer idprecioProducto) {
		this.idprecioProducto = idprecioProducto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_IDUsuarioModifica", nullable = false)
	public Usuario getUsuarioByUsuarioIdusuarioModifica() {
		return this.usuarioByUsuarioIdusuarioModifica;
	}

	public void setUsuarioByUsuarioIdusuarioModifica(
			Usuario usuarioByUsuarioIdusuarioModifica) {
		this.usuarioByUsuarioIdusuarioModifica = usuarioByUsuarioIdusuarioModifica;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "tipoprecio_IDTipoPrecio", nullable = false)
	public Tipoprecio getTipoprecio() {
		return this.tipoprecio;
	}

	public void setTipoprecio(Tipoprecio tipoprecio) {
		this.tipoprecio = tipoprecio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_IDUsuarioAlta", nullable = false)
	public Usuario getUsuarioByUsuarioIdusuarioAlta() {
		return this.usuarioByUsuarioIdusuarioAlta;
	}

	public void setUsuarioByUsuarioIdusuarioAlta(
			Usuario usuarioByUsuarioIdusuarioAlta) {
		this.usuarioByUsuarioIdusuarioAlta = usuarioByUsuarioIdusuarioAlta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "producto_IDProducto", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "tienda_IDTienda", nullable = false)
	public Tienda getTienda() {
		return this.tienda;
	}

	public void setTienda(Tienda tienda) {
		this.tienda = tienda;
	}

	@Column(name = "PrecioProducto", nullable = false, precision = 8)
	public double getPrecioProducto() {
		return this.precioProducto;
	}

	public void setPrecioProducto(double precioProducto) {
		this.precioProducto = precioProducto;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaAlta", length = 19)
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaMod", length = 19)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Column(name = "Estatus", nullable = false)
	public Integer getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Integer estatus) {
		this.estatus = estatus;
	}

}
