package com.quimera.corptextiljt.model;

import static javax.persistence.GenerationType.IDENTITY;

// Generated Dec 23, 2017 11:54:35 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name = "producto", catalog = "jtextpricesbd")
public class Producto implements java.io.Serializable {

	private Integer idproducto;
	private String nombreProducto;
	private Double ancho;
	private Double rendimiento;
	private Integer estatus;
	private Set<Precioproducto> precioproductos = new HashSet<Precioproducto>(0);
	private Set<Logprecioproducto> logprecioproductos = new HashSet<Logprecioproducto>(0);

	public Producto() {
	}

	public Producto(String nombreProducto, Integer estatus) {
		this.nombreProducto = nombreProducto;
		this.estatus = estatus;
	}

	public Producto(String nombreProducto, Double ancho, Double rendimiento,
			Integer estatus, Set<Precioproducto> precioproductos, Set<Logprecioproducto> logprecioproductos) {
		this.nombreProducto = nombreProducto;
		this.ancho = ancho;
		this.rendimiento = rendimiento;
		this.estatus = estatus;
		this.precioproductos = precioproductos;
		this.logprecioproductos = logprecioproductos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDProducto", unique = true, nullable = false)
	public Integer getIdproducto() {
		return this.idproducto;
	}

	public void setIdproducto(Integer idproducto) {
		this.idproducto = idproducto;
	}

	@Column(name = "Nombre Producto", nullable = false, length = 40)
	public String getNombreProducto() {
		return this.nombreProducto;
	}

	public void setNombreProducto(String nombreProducto) {
		this.nombreProducto = nombreProducto;
	}

	@Column(name = "Ancho", precision = 6)
	public Double getAncho() {
		return this.ancho;
	}

	public void setAncho(Double ancho) {
		this.ancho = ancho;
	}

	@Column(name = "Rendimiento", precision = 6)
	public Double getRendimiento() {
		return this.rendimiento;
	}

	public void setRendimiento(Double rendimiento) {
		this.rendimiento = rendimiento;
	}

	@Column(name = "Estatus", nullable = false)
	public Integer getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Integer estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "producto")
	public Set<Precioproducto> getPrecioproductos() {
		return this.precioproductos;
	}

	public void setPrecioproductos(Set<Precioproducto> precioproductos) {
		this.precioproductos = precioproductos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "producto")
	public Set<Logprecioproducto> getLogprecioproductos() {
		return this.logprecioproductos;
	}

	public void setLogprecioproductos(Set<Logprecioproducto> logprecioproductos) {
		this.logprecioproductos = logprecioproductos;
	}

}
