package com.quimera.corptextiljt.model;

// Generated Dec 23, 2017 11:54:35 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name = "rol", catalog = "jtextpricesbd", uniqueConstraints = @UniqueConstraint(columnNames = "NombreRol"))
public class Rol implements java.io.Serializable {

	private Integer idrol;
	private String nombreRol;
	private Set<Acceso> accesos = new HashSet<Acceso>(0);

	public Rol() {
	}

	public Rol(String nombreRol) {
		this.nombreRol = nombreRol;
	}

	public Rol(String nombreRol, Set<Acceso> accesos) {
		this.nombreRol = nombreRol;
		this.accesos = accesos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDRol", unique = true, nullable = false)
	public Integer getIdrol() {
		return this.idrol;
	}

	public void setIdrol(Integer idrol) {
		this.idrol = idrol;
	}

	@Column(name = "NombreRol", unique = true, nullable = false, length = 20)
	public String getNombreRol() {
		return this.nombreRol;
	}

	public void setNombreRol(String nombreRol) {
		this.nombreRol = nombreRol;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
	public Set<Acceso> getAccesos() {
		return this.accesos;
	}

	public void setAccesos(Set<Acceso> accesos) {
		this.accesos = accesos;
	}

}
