package com.quimera.corptextiljt.model;

// Generated Dec 23, 2017 11:54:35 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tienda generated by hbm2java
 */
@Entity
@Table(name = "tienda", catalog = "jtextpricesbd")
public class Tienda implements java.io.Serializable {

	private int idtienda;
	private Clasificaciontienda clasificaciontienda;
	private String nombreTienda;
	private int estatus;
	private Set<Precioproducto> precioproductos = new HashSet<Precioproducto>(0);

	public Tienda() {
	}

	public Tienda(Clasificaciontienda clasificaciontienda, String nombreTienda,
			int estatus) {
		this.clasificaciontienda = clasificaciontienda;
		this.nombreTienda = nombreTienda;
		this.estatus = estatus;
	}

	public Tienda(Clasificaciontienda clasificaciontienda, String nombreTienda,
			int estatus, Set<Precioproducto> precioproductos) {
		this.clasificaciontienda = clasificaciontienda;
		this.nombreTienda = nombreTienda;
		this.estatus = estatus;
		this.precioproductos = precioproductos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDTienda", unique = true, nullable = false)
	public int getIdtienda() {
		return this.idtienda;
	}

	public void setIdtienda(int idtienda) {
		this.idtienda = idtienda;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clasificaciontienda_IDClasificacionTienda", nullable = false)
	public Clasificaciontienda getClasificaciontienda() {
		return this.clasificaciontienda;
	}

	public void setClasificaciontienda(Clasificaciontienda clasificaciontienda) {
		this.clasificaciontienda = clasificaciontienda;
	}

	@Column(name = "Nombre Tienda", nullable = false, length = 30)
	public String getNombreTienda() {
		return this.nombreTienda;
	}

	public void setNombreTienda(String nombreTienda) {
		this.nombreTienda = nombreTienda;
	}

	@Column(name = "Estatus", nullable = false)
	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tienda")
	public Set<Precioproducto> getPrecioproductos() {
		return this.precioproductos;
	}

	public void setPrecioproductos(Set<Precioproducto> precioproductos) {
		this.precioproductos = precioproductos;
	}

}
