package com.quimera.corptextiljt.model;

// Generated Dec 23, 2017 11:54:35 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipoprecio generated by hbm2java
 */
@Entity
@Table(name = "tipoprecio", catalog = "jtextpricesbd")
public class Tipoprecio implements java.io.Serializable {

	private int idtipoPrecio;
	private String nombrePrecio;
	private Set<Precioproducto> precioproductos = new HashSet<Precioproducto>(0);
	private Set<Logprecioproducto> logprecioproductos = new HashSet<Logprecioproducto>(0);

	public Tipoprecio() {
	}

	public Tipoprecio(String nombrePrecio) {
		this.nombrePrecio = nombrePrecio;
	}

	public Tipoprecio(String nombrePrecio, Set<Precioproducto> precioproductos,
			Set<Logprecioproducto> logprecioproductos) {
		this.nombrePrecio = nombrePrecio;
		this.precioproductos = precioproductos;
		this.logprecioproductos = logprecioproductos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDTipoPrecio", unique = true, nullable = false)
	public int getIdtipoPrecio() {
		return this.idtipoPrecio;
	}

	public void setIdtipoPrecio(int idtipoPrecio) {
		this.idtipoPrecio = idtipoPrecio;
	}

	@Column(name = "NombrePrecio", nullable = false, length = 20)
	public String getNombrePrecio() {
		return this.nombrePrecio;
	}

	public void setNombrePrecio(String nombrePrecio) {
		this.nombrePrecio = nombrePrecio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoprecio")
	public Set<Precioproducto> getPrecioproductos() {
		return this.precioproductos;
	}

	public void setPrecioproductos(Set<Precioproducto> precioproductos) {
		this.precioproductos = precioproductos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoprecio")
	public Set<Logprecioproducto> getLogprecioproductos() {
		return this.logprecioproductos;
	}

	public void setLogprecioproductos(Set<Logprecioproducto> logprecioproductos) {
		this.logprecioproductos = logprecioproductos;
	}

}
